Use Column instead of ManyToManyColumn in ErrorsTable
This fixes the "AttributeError: 'list' object has no attribute 'exists'"
error from django-tables2. Also add a render_errors method to print
the errors in a more nicely formatted way.